/** Arabic for every user-facing string in menu.ts, keyed by the exact English string. */
export const MENU_AR: Record<string, string> = {
  // ── Food ──────────────────────────────────────────────
  "Food": "الأكل",
  "Grill, feteer, pasta and the rest of the kitchen.": "مشويات وفطير وباستا وباقي المطبخ.",

  "Main course": "الأطباق الرئيسية",
  "Aroma Rib Eye Steak": "ستيك ريب آي أروما",
  "Premium Angus rib eye, sun dried tomato mashed potato, mixed salad": "ريب آي أنجس بريميوم، بطاطس مهروسة بالطماطم المجففة، سلطة مشكلة",
  "Smoked Angus Brisket": "بريسكت أنجس مدخن",
  "Premium Angus brisket, slow cooked, creamy mashed potatoes": "بريسكت أنجس بريميوم مطهو على نار هادية، بطاطس مهروسة بالكريمة",
  "Salmon Lemon Butter": "سلمون بصوص الليمون والزبدة",
  "Grilled salmon / sautéed vegetables / mashed potatoes / lemon butter sauce": "سلمون مشوي / خضار سوتيه / بطاطس مهروسة / صوص ليمون بالزبدة",
  "Aroma Beef Fillet": "فيليه لحم أروما",
  "Beef fillet (baladi) / potato cubes / mixed green salad / black pepper or mushroom sauce": "فيليه بلدي / مكعبات بطاطس / سلطة خضرا مشكلة / صوص فلفل أسود أو صوص مشروم",
  "Beef Stroganoff": "بيف ستروجانوف",
  "Beef slices / stroganoff sauce / mushroom / yellow basmati rice": "شرائح لحم / صوص ستروجانوف / مشروم / أرز بسمتي أصفر",
  "Osso Buco": "أوسو بوكو",
  "Osso buco / safflower lemon demi glace / roasted mushroom / mashed potatoes": "أوسو بوكو / ديمي جلاس بالليمون والعصفر / مشروم مشوي / بطاطس مهروسة",
  "Seafood Mix Tajin": "طاجن سي فود مشكل",
  "A mix of seafood in white sauce, topped with cheese": "تشكيلة سي فود بالصوص الأبيض، مغطاة بالجبنة",
  "Liver Shish Kebab": "شيش كبدة",
  "Aroma Grilled Chicken": "فراخ مشوية أروما",
  "Grilled chicken breasts / potato cubes / mushroom sauce / mixed green salad": "صدور فراخ مشوية / مكعبات بطاطس / صوص مشروم / سلطة خضرا مشكلة",
  "Grilled Chicken Mesahab": "فراخ مسحب مشوية",
  "Half chicken / sautéed vegetables / yellow basmati rice / thomeyya": "نص فرخة / خضار سوتيه / أرز بسمتي أصفر / تومية",
  "Chicken Pastrami Roll": "رول فراخ بالباسترامي",
  "Meatballs Pot": "طاجن ميت بولز",
  "Meatballs in brown sauce with vegetables, served with yellow basmati rice": "ميت بولز بالصوص البني مع الخضار، تقدم مع أرز بسمتي أصفر",
  "Country Fried Chicken": "كانتري فرايد تشيكن",

  "Feteer": "فطير",
  "Meshaltet": "فطير مشلتت",
  "Served with cream / molasses / tahini / gebna kadeema": "يقدم مع قشطة / عسل أسود / طحينة / جبنة قديمة",
  "Soguk Feteer": "فطير سجق",
  "Soguk / mozzarella / roumi cheese / tomatoes / olives / bell pepper": "سجق / موتزاريلا / جبنة رومي / طماطم / زيتون / فلفل ألوان",
  "Mixed Beef Feteer": "فطير لحوم مشكلة",
  "Soguk / ground beef / pastrami / mozzarella / tomatoes": "سجق / لحمة مفرومة / باسترامي / موتزاريلا / طماطم",
  "Chicken Feteer": "فطير فراخ",
  "Chicken / mushroom / olives / mozzarella / roumi / cheddar / spinach": "فراخ / مشروم / زيتون / موتزاريلا / رومي / شيدر / سبانخ",
  "Basterma Feteer": "فطير بسطرمة",
  "Mix Cheese Feteer": "فطير مكس جبن",
  "Red cheddar / cream cheese / mozzarella / halloumi / pesto sauce": "شيدر أحمر / كريم تشيز / موتزاريلا / حلومي / صوص بيستو",
  "Lotus and Nutella Feteer": "فطير لوتس ونوتيلا",
  "Nutella Marshmallow Feteer": "فطير نوتيلا ومارشميلو",
  "Nutella / marshmallow / custard / white chocolate flakes": "نوتيلا / مارشميلو / كاسترد / رقائق شوكولاتة بيضاء",
  "Lotus Feteer": "فطير لوتس",
  "Boghasha Feteer": "فطير بغاشة",
  "Condensed milk / vanilla / hot milk / powdered sugar": "لبن مكثف / فانيليا / لبن سخن / سكر بودرة",
  "Custard Feteer Roll": "رول فطير بالكاسترد",

  "Burgers and sandwiches": "برجر وساندويتشات",
  "Seafood Mix Sandwich": "ساندويتش سي فود مكس",
  "Vienna bread / seafood mix / pico de gallo / mayonnaise / ranch sauce / fries": "عيش فينو / سي فود مكس / بيكو دي جايو / مايونيز / صوص رانش / بطاطس محمرة",
  "Steak Sandwich": "ساندويتش ستيك",
  "Ciabatta / beef slices / capsicum / onion / cheddar / brown sauce / fries": "شياباتا / شرائح لحم / فلفل ألوان / بصل / شيدر / صوص بني / بطاطس محمرة",
  "Mushroom Cheeseburger": "مشروم تشيز برجر",
  "Lettuce / tomatoes / pickled cucumber / mushroom sauce / cheese sauce / fries": "خس / طماطم / خيار مخلل / صوص مشروم / صوص جبنة / بطاطس محمرة",
  "Aroma Chili Burger": "تشيلي برجر أروما",
  "Lettuce / tomatoes / pickled cucumber / jalapeño / chilli sauce / cheese sauce / fries": "خس / طماطم / خيار مخلل / هالابينو / صوص تشيلي / صوص جبنة / بطاطس محمرة",
  "Classic Cheeseburger": "كلاسيك تشيز برجر",
  "Lettuce / tomatoes / pickled cucumber / cheese sauce / fries": "خس / طماطم / خيار مخلل / صوص جبنة / بطاطس محمرة",
  "Crispy Fried Chicken Bun": "كريسبي تشيكن بن",
  "Fried chicken / lettuce / tomatoes / pickled cucumber / pink sauce / ranch / fries": "فراخ مقلية / خس / طماطم / خيار مخلل / بينك صوص / رانش / بطاطس محمرة",
  "Grilled Chicken Wrap": "راب فراخ مشوية",
  "Tortilla / lettuce / mozzarella / cheddar / carrots / sumac onion / ranch / fries": "تورتيلا / خس / موتزاريلا / شيدر / جزر / بصل بالسماق / رانش / بطاطس محمرة",
  "Club Sandwich": "كلوب ساندويتش",
  "Toast / chicken / eggs / cheddar / smoked turkey / lettuce / tomatoes / mayonnaise / fries": "توست / فراخ / بيض / شيدر / تركي مدخن / خس / طماطم / مايونيز / بطاطس محمرة",
  "Tuna Melt Sandwich": "تونة ميلت ساندويتش",
  "Toast / capsicum / mustard / capers / mayonnaise / fries": "توست / فلفل ألوان / مستردة / كبر / مايونيز / بطاطس محمرة",

  "Salads": "السلطات",
  "Steak Salad": "سلطة ستيك",
  "Grilled steak / arugula / avocado / roasted mushroom / cherry tomatoes / parmesan / gorgonzola dressing": "ستيك مشوي / جرجير / أفوكادو / مشروم مشوي / طماطم شيري / بارميزان / دريسنج جورجونزولا",
  "Honey Garlic Shrimp Salad": "سلطة جمبري بالعسل والتوم",
  "Shrimps / arugula / cherry tomatoes / roasted capsicum / lettuce / roasted almonds": "جمبري / جرجير / طماطم شيري / فلفل ألوان مشوي / خس / لوز محمص",
  "Salmon Salad": "سلطة سلمون",
  "Smoked salmon / lettuce / arugula / cherry tomatoes / pineapple / sumac onion / capers": "سلمون مدخن / خس / جرجير / طماطم شيري / أناناس / بصل بالسماق / كبر",
  "Chicken Caesar Salad": "سلطة سيزر بالفراخ",
  "Chicken Ranch Salad": "سلطة فراخ رانش",
  "Grilled chicken / lettuce / cherry tomatoes / caramelized walnuts / radish / croutons / parmesan": "فراخ مشوية / خس / طماطم شيري / عين جمل مكرمل / فجل / كروتون / بارميزان",
  "Halloumi Avocado Salad": "سلطة حلومي وأفوكادو",
  "Halloumi / avocado spread / arugula / lettuce / pico de gallo / radish / pesto / ranch mint dressing": "حلومي / سبريد أفوكادو / جرجير / خس / بيكو دي جايو / فجل / بيستو / دريسنج رانش بالنعناع",
  "Quinoa Salad": "سلطة كينوا",

  "Appetizers": "المقبلات",
  "Beef Quesadilla": "كاساديا لحم",
  "Beef / cheddar / mozzarella / sweet corn / kidney beans / roasted capsicum / sour cream / guacamole": "لحم / شيدر / موتزاريلا / ذرة حلوة / فاصوليا حمرا / فلفل ألوان مشوي / ساور كريم / واكامولي",
  "Shrimps and Calamari Basket": "باسكت جمبري وكاليماري",
  "Fried shrimps / fried calamari / ranch sauce": "جمبري مقلي / كاليماري مقلي / صوص رانش",
  "Chicken Quesadilla": "كاساديا فراخ",
  "Chicken / cheddar / mozzarella / sweet corn / kidney beans / roasted capsicum / sour cream / guacamole": "فراخ / شيدر / موتزاريلا / ذرة حلوة / فاصوليا حمرا / فلفل ألوان مشوي / ساور كريم / واكامولي",
  "Hawawshi": "حواوشي",
  "Shrimps Cilantro": "جمبري بالكزبرة",
  "Shrimps / white lemon sauce / cilantro / nachos": "جمبري / صوص أبيض بالليمون / كزبرة / ناتشوز",
  "Chicken Croquettes": "كروكيت فراخ",
  "Chicken balls / mozzarella / red cheddar / parmesan / herbs / onion / pink sauce": "كرات فراخ / موتزاريلا / شيدر أحمر / بارميزان / أعشاب / بصل / بينك صوص",
  "Chicken Liver": "كبدة فراخ",
  "Chicken liver / spinach / roasted almonds / cherry tomatoes / lemon cream sauce / nachos": "كبدة فراخ / سبانخ / لوز محمص / طماطم شيري / صوص كريمة بالليمون / ناتشوز",
  "Soguk": "سجق",

  "Pasta and risotto": "باستا وريزوتو",
  "Beef Pesto Fettuccine": "فيتوتشيني لحم بالبيستو",
  "Seafood Fettuccini": "فيتوتشيني سي فود",
  "Shrimps / calamari / fish / white sauce / parmesan / sprouts": "جمبري / كاليماري / سمك / صوص أبيض / بارميزان / براعم",
  "Chicken Penne Alfredo": "بيني ألفريدو بالفراخ",
  "Grilled chicken / alfredo sauce / mushroom / parmesan": "فراخ مشوية / صوص ألفريدو / مشروم / بارميزان",
  "Negresco Fried Chicken": "نجرسكو بالفراخ المقلية",
  "Meatballs Fettuccini": "فيتوتشيني ميت بولز",
  "Meatballs / Aroma red sauce / parmesan": "ميت بولز / صوص أحمر أروما / بارميزان",
  "Spaghetti Bolognese": "سباجيتي بولونيز",
  "Bolognese sauce / basil / parmesan": "صوص بولونيز / ريحان / بارميزان",
  "Chicken Liver Penne": "بيني بكبدة الفراخ",
  "Chicken liver / cherry tomatoes / Aroma red sauce / white sauce / sprouts": "كبدة فراخ / طماطم شيري / صوص أحمر أروما / صوص أبيض / براعم",
  "Shrimp Risotto": "ريزوتو جمبري",
  "Beef Risotto": "ريزوتو لحم",
  "Truffle Mushroom Risotto": "ريزوتو مشروم بالترافل",

  "Paella": "باييا",
  "Seafood Paella": "باييا سي فود",
  "Shrimps / calamari / fish / mussels / paella rice / peas / carrots / cilantro / parsley": "جمبري / كاليماري / سمك / بلح بحر / أرز باييا / بسلة / جزر / كزبرة / بقدونس",
  "Chicken Paella": "باييا فراخ",
  "Chicken / paella rice / peas / carrots / cilantro / parsley": "فراخ / أرز باييا / بسلة / جزر / كزبرة / بقدونس",
  "Vegetables Paella": "باييا خضار",
  "Zucchini / broccoli / mushroom / capsicum / paella rice / peas / carrots / cilantro / parsley": "كوسة / بروكلي / مشروم / فلفل ألوان / أرز باييا / بسلة / جزر / كزبرة / بقدونس",

  "Pizza": "بيتزا",
  "Pizza Chicken Truffle Mushroom": "بيتزا فراخ بالمشروم والترافل",
  "Shrimp Pizza": "بيتزا جمبري",
  "Pizza Quattro Formaggi": "بيتزا كواترو فورماجي",
  "Pizza Pepperoni": "بيتزا بيبروني",
  "Buffalo Cheese Pizza": "بيتزا جبنة بافلو",

  "Soups": "الشوربة",
  "Shrimps Ginger and Carrot Soup": "شوربة جمبري بالجنزبيل والجزر",
  "Shrimps / ginger / carrots / onion / garlic / turmeric / coconut cream": "جمبري / جنزبيل / جزر / بصل / توم / كركم / كريمة جوز هند",
  "Wild Mushroom": "شوربة وايلد مشروم",
  "Mushroom soup / pesto sauce": "شوربة مشروم / صوص بيستو",
  "Chicken Corn Soup": "شوربة فراخ بالذرة",
  "Chicken cubes / cream soup / sweet corn / potatoes": "مكعبات فراخ / شوربة كريمة / ذرة حلوة / بطاطس",

  // ── Drinks ────────────────────────────────────────────
  "Drinks": "المشروبات",
  "Hot, cold, fresh and blended.": "سخن وساقع، فريش ومخفوق.",

  "Hot drinks": "مشروبات سخنة",
  "Pistachio Latte": "لاتيه بستاشيو",
  "Sahlab": "سحلب",
  "Spanish Latte": "سبانيش لاتيه",
  "Salted Caramel Latte": "لاتيه سولتد كراميل",
  "Health Boost": "هيلث بوست",
  "Cappuccino Caramel": "كابتشينو كراميل",
  "Coffee Lotus": "قهوة لوتس",
  "Homoss Elsham": "حمص الشام",
  "White Mocha": "وايت موكا",
  "Espresso Double": "إسبريسو دبل",
  "Cappuccino": "كابتشينو",
  "Cafe Latte": "كافيه لاتيه",
  "Cafe Mocha": "كافيه موكا",
  "Aroma Gold": "أروما جولد",
  "Apple Cider": "سايدر تفاح",
  "Hot Chocolate": "هوت شوكليت",
  "Nutella Coffee": "قهوة نوتيلا",
  "American Coffee": "قهوة أمريكي",
  "Cinnamon Milk": "لبن بالقرفة",
  "Espresso": "إسبريسو",
  "Turkish Coffee (Mehawweg)": "قهوة تركي (محوج)",
  "Turkish Coffee": "قهوة تركي",
  "Tea": "شاي",
  "Herbs": "أعشاب",

  "Cold drinks": "مشروبات ساقعة",
  "Redbull Mix Berries": "ريد بول ميكس بيريز",
  "Iced Salted Caramel Latte": "آيس لاتيه سولتد كراميل",
  "Mojito Passion Fruit": "موهيتو باشن فروت",
  "Pistachio Ice Latte": "آيس لاتيه بستاشيو",
  "Cookies Ice Latte": "آيس لاتيه كوكيز",
  "Kiwi Lemonade": "ليموناضة كيوي",
  "Iced Spanish Latte": "آيس سبانيش لاتيه",
  "Iced White Mocha Latte": "آيس وايت موكا لاتيه",
  "Mocha Frappe": "فرابيه موكا",
  "Latte Frappe": "فرابيه لاتيه",
  "Ice Caramel Macchiato": "آيس كراميل ماكياتو",
  "Sunshine": "صن شاين",
  "Ice Chocolate": "آيس شوكليت",
  "Oreo Shake": "أوريو شيك",
  "Milkshake": "ميلك شيك",
  "Apple Angel": "آبل أنجل",
  "Ice Latte": "آيس لاتيه",
  "Ice Tea": "آيس تي",
  "Peach, passion fruit, apple or coconut": "خوخ، باشن فروت، تفاح أو جوز هند",
  "Cherry Cola": "شيري كولا",

  "Matcha": "ماتشا",
  "Hot Pistachio Matcha": "ماتشا بستاشيو سخنة",
  "Iced Spanish Matcha": "آيس سبانيش ماتشا",
  "Spanish Matcha": "سبانيش ماتشا",
  "Salted Caramel Matcha": "ماتشا سولتد كراميل",
  "Iced Strawberry Matcha": "آيس ماتشا فراولة",
  "Blended Pistachio Matcha": "ماتشا بستاشيو بلندد",
  "Hot Matcha": "ماتشا سخنة",
  "Iced Mango Vanilla Matcha": "آيس ماتشا مانجو فانيليا",

  "Juices and smoothies": "عصائر وسموزي",
  "Fresh Avocado Cocktail": "كوكتيل أفوكادو فريش",
  "Pina Colada": "بينا كولادا",
  "Banana Berries": "بنانا بيريز",
  "Mango Colada": "مانجو كولادا",
  "Strawberry Colada": "ستروبري كولادا",
  "Fresh Kiwi Cocktail": "كوكتيل كيوي فريش",
  "Mango Smoothie": "سموزي مانجو",
  "Lemon Mint": "ليمون نعناع",
  "Strawberries Smoothie": "سموزي فراولة",
  "Orange Strawberries": "برتقال فراولة",
  "Watermelon Smoothie": "سموزي بطيخ",
  "Fresh Mango Juice": "عصير مانجو فريش",
  "Fresh Lemon Juice": "عصير ليمون فريش",
  "Fresh Orange Juice": "عصير برتقال فريش",
  "Fresh Strawberry Juice": "عصير فراولة فريش",
  "Fresh Guava Juice": "عصير جوافة فريش",
  "Fresh Fig": "تين فريش",
  "Banana and Milk": "موز باللبن",

  "Yogurt mixes": "زبادي ميكس",
  "Mix Berry": "ميكس بيري",
  "Strawberries": "فراولة",
  "Peach": "خوخ",
  "Honey": "عسل",

  "Soft drinks and water": "مشروبات غازية ومياه",
  "Red Bull": "ريد بول",
  "Fayrouz Pineapple": "فيروز أناناس",
  "Birel": "بيريل",
  "Non alcoholic": "بدون كحول",
  "Sparkling Water": "مياه فوارة",
  "Pepsi": "بيبسي",
  "Diet Pepsi": "بيبسي دايت",
  "7 Up": "سفن أب",
  "Mirinda Orange": "ميرندا برتقال",
  "Water (large)": "مياه (كبيرة)",
  "Water (small)": "مياه (صغيرة)",

  // ── Breakfast (section and category share the label) ─
  "Breakfast": "الفطار",
  "Oriental trays, eggs and benedicts, served through the morning.": "صواني فطار شرقي، بيض وبنديكت، طول الصبح.",
  "Full Oriental Breakfast Tray": "صينية فطار شرقي كاملة",
  "Feteer meshaltet / foul / eggs / tameyya / gebna beida / labna / salad / molasses / gebna adeema": "فطير مشلتت / فول / بيض / طعمية / جبنة بيضا / لبنة / سلطة / عسل أسود / جبنة قديمة",
  "Oriental Breakfast Tray": "صينية فطار شرقي",
  "Foul / eggs / tameyya / gebna beida / labna / salad": "فول / بيض / طعمية / جبنة بيضا / لبنة / سلطة",
  "Salmon Avocado Omelet": "أومليت سلمون وأفوكادو",
  "Smoked salmon, avocado, capers, labna, onion and sumac, with herb potato cubes and salad": "سلمون مدخن، أفوكادو، كبر، لبنة، بصل وسماق، مع مكعبات بطاطس بالأعشاب وسلطة",
  "Smoked Salmon Eggs Benedict": "إيجز بنديكت بالسلمون المدخن",
  "Two poached eggs, smoked salmon, arugula, avocado, spinach and hollandaise": "بيضتين بوشيه، سلمون مدخن، جرجير، أفوكادو، سبانخ وصوص هولنديز",
  "Avocado and Beef Bacon Benedict": "بنديكت أفوكادو وبيف بيكون",
  "Two poached eggs, beef bacon, arugula, guacamole and hollandaise": "بيضتين بوشيه، بيف بيكون، جرجير، واكامولي وصوص هولنديز",
  "Mushroom Cheese Spinach Omelet": "أومليت مشروم وجبنة وسبانخ",
  "Cheddar, fresh mushroom, spinach and cherry tomatoes, with herb potato cubes and salad": "شيدر، مشروم فريش، سبانخ وطماطم شيري، مع مكعبات بطاطس بالأعشاب وسلطة",
  "Pastrami Eggs Casserole": "طاجن بيض بالباسترامي",
  "Sunny side up eggs with pastrami, tomatoes and arugula": "بيض عيون بالباسترامي والطماطم والجرجير",
  "Smoked Turkey Benedict": "بنديكت تركي مدخن",
  "Two poached eggs, smoked turkey, mayonnaise, arugula, sun dried tomatoes and hollandaise": "بيضتين بوشيه، تركي مدخن، مايونيز، جرجير، طماطم مجففة وصوص هولنديز",
  "Hash Brown Eggs and Cheese Casserole": "طاجن هاش براون بالبيض والجبنة",
  "Eggs with feta, fries, broccoli and tomatoes": "بيض بجبنة فيتا، بطاطس محمرة، بروكلي وطماطم",
  "Egg White Cheese and Olives Omelet": "أومليت بياض بيض بالجبنة والزيتون",
  "Feta, black olives, mushroom and bell pepper, with herb potato cubes and salad": "فيتا، زيتون أسود، مشروم وفلفل ألوان، مع مكعبات بطاطس بالأعشاب وسلطة",
  "Eggs Shakshooka Casserole": "طاجن بيض شكشوكة",
  "Sunny side up eggs with oriental shakshooka mix": "بيض عيون مع خلطة شكشوكة شرقي",
  "Focaccia Spanish Egg": "فوكاتشا بالبيض الإسباني",
  "Flat Bread, Smoked Salmon and Cheese": "فلات بريد سلمون مدخن وجبنة",
  "Flat bread with cream cheese, smoked salmon and capers": "فلات بريد بالكريم تشيز والسلمون المدخن والكبر",
  "Chicken Ranch Croissant": "كرواسون فراخ رانش",
  "Flat Bread, Minced Beef and Eggs": "فلات بريد لحمة مفرومة وبيض",
  "Flat bread with herbed minced beef, eggs and parsley": "فلات بريد بلحمة مفرومة بالأعشاب وبيض وبقدونس",
  "Turkey Omelette Croissant": "كرواسون أومليت تركي",
  "Flat Bread, Beef Bacon and Eggs": "فلات بريد بيف بيكون وبيض",
  "Flat bread with beef bacon, cherry tomatoes and eggs": "فلات بريد ببيف بيكون وطماطم شيري وبيض",
  "Omelette Hot Dogs Croissant": "كرواسون أومليت هوت دوج",
  "Mixed Cheese Croissant": "كرواسون مكس جبن",

  // ── Dessert (section and category share the label) ───
  "Dessert": "الحلو",
  "Pancakes, waffles and the pastry counter.": "بان كيك ووافل وحلويات الفاترينة.",
  "Four Seasons Waffle": "وافل فور سيزونز",
  "Cream Brûlée French Toast": "فرنش توست كريم بروليه",
  "Oreo Ice Cream Waffle": "وافل أوريو بالآيس كريم",
  "Waffle Croissant": "كرواسون وافل",
  "Make your own: pistachio, Nutella or strawberry": "اختار على مزاجك: بستاشيو، نوتيلا أو فراولة",
  "Pistachio Pancake": "بان كيك بستاشيو",
  "Nutella Ice Cream Pancake": "بان كيك نوتيلا بالآيس كريم",
  "Chocolate Lava Cake with Ice Cream": "لافا كيك شوكولاتة بالآيس كريم",
  "Nutella Pancake": "بان كيك نوتيلا",
  "Lotus Pancake": "بان كيك لوتس",
  "Blueberry Cheesecake": "تشيز كيك بلوبيري",
  "Strawberry Cheesecake": "تشيز كيك فراولة",
  "Chocolate Fudge": "شوكولاتة فادج",
  "Tiramisu": "تيراميسو",
  "Eclair Nutella": "إكلير نوتيلا",
  "Eclair Caramel": "إكلير كراميل",
  "Om Ali": "أم علي",
  "Ice Cream": "آيس كريم",
  "French vanilla, chocolate, strawberry or mango": "فرنش فانيليا، شوكولاتة، فراولة أو مانجو",

  // ── Kids (section and category share the label) ──────
  "Kids": "الأطفال",
  "Smaller plates for the table's youngest.": "أطباق أصغر لأصغر واحد على الترابيزة.",
  "Pasta Meatballs": "باستا ميت بولز",
  "Pasta Crispy Chicken": "باستا كريسبي تشيكن",
  "Chicken Strips": "تشيكن ستريبس",
};
